services:

  # mqtt-broker:
  #   build:
  #     context: ./mosquitto
  #   restart: unless-stopped
  #   ports:
  #     - "1883:1883"
  #   volumes:
  #     - ./mosquitto/log:/mosquitto/log:cached

  master:
    build: ./master
    environment:
      MAX_PLAYERS: ${MAX_PLAYERS}
      MQTT_BROKER_HOST: ${MQTT_BROKER_HOST}
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT}
      USERNAME: ${MASTER_USERNAME}
      PASSWORD: ${MASTER_PASSWORD}
    # depends_on:
    #   - mqtt-broker
